src/mapbox/Colors.js
=> changed colors to clients brand colors

debug.log, public/index.html, src/App.js, src/index.css
Futura is the font that is used by the Greater Chicago Food Depository for their branding and website.  Updated the left & right menus with this font.
=> added the font Futura to the left and right menus

src/App.js, src/mapbox/NavigationControlsStyles.js, src/redux/viewportReducer.js
Add +,- zoom buttons #12 Issue
- Added +/- zoom buttons
- Confined max and min zoom so that map is not too zoom out/in
=> +/- Zoom buttons

src/App.css, src/App.js, src/components/RenderToolTip.js, src/mapbox/CountyLayer.js, src/mapbox/Map.js, src/mapbox/ZipcodeLayer.js
Resolves Issue #11 
Mapbox components and logic from App.js is extracted into separate components.
=> Extract from App.js into separate components

src/App.css, src/App.js, src/redux/viewportReducer.js
This is currently a draft pull request due to 1 issue - I tried to create as much of the toggle buttons in CSS as possible, but I can't get the button to go from left to right when active/inactive.  I am aware there are other ways to do this (including using JavaScript) so I am putting here for feedback.  I based the design of the toggle button on this:
https://codepen.io/avstorm/pen/jOEpBLW
=> designed righthand menu

src/mapbox/Map.test.js
Mock mapbox and test render with jest.
=> jest test mapbox render

src/App.js, src/mapbox/Map.js, src/redux/countyDataReducer.js, src/redux/store.js, src/redux/zipCodeDataReducer.js
received feature data for county and zipcodes from API/Firebase
=> county and zipcodes features data thunks added

README.md
=> Update README to have Netlify status

src/App.css, src/App.js, src/components/LeftHandMenu/DatasetSelector/DatasetSelector.css, src/components/LeftHandMenu/DatasetSelector/DatasetSelector.js, src/components/LeftHandMenu/LeftHandMenu.css, src/components/LeftHandMenu/LeftHandMenu.js, src/components/LeftHandMenu/ZoomToBoundsMenu.css, src/components/LeftHandMenu/ZoomToBoundsMenu.js, src/components/RightHandMenu/DonutChart/Donut.css, src/components/RightHandMenu/DonutChart/Donut.js, src/components/RightHandMenu/DonutChart/Legend/Legend.css, src/components/RightHandMenu/DonutChart/Legend/Legend.js, src/components/RightHandMenu/DonutChart/UnEqualDonut/UnequalDonut.js, src/components/RightHandMenu/RightHandMenu.js, src/components/RightHandMenu/ToggleSelect/ToggleSelect.js, src/components/RightHandMenu/dataOptions.js, src/components/Utility/RadioSelect/RadioSelect.css, src/components/Utility/RadioSelect/RadioSelect.js, src/components/Utility/RadioSelect/RadioSelect2.js, src/components/Utility/filterFeatChart.js, src/components/ZoomToBoundsMenu.test.js, src/mapbox/Map.js, src/mapbox/ZipcodeLayer.js, src/redux/selectedFeatReducer.js, src/redux/store.js
Right Hand Component: 
- All features on Right Hand menu working except SNAP data.
- Zoom to Bounds Button can also select the required county Data.
Next Sprint
- need to modify selectFeat slice to add the RightHand-SubSelectionMenu
- Incorporate SNAP data
=> Right hand component

src/components/RightHandMenu/LinkToSource/LinkToSource.css, src/components/RightHandMenu/LinkToSource/LinkToSource.js, src/components/RightHandMenu/RightHandMenu.css, src/components/RightHandMenu/RightHandMenu.js
[ticket](https://trello.com/c/44JRhrRO/147-user-can-view-the-year-of-the-datasource-link-before-clicking-into-it)
Created a new component for the data source link for RightHandMenu. Added switch statements to determine what text should be displayed as the link. The links still don't actually go anywhere.
=> Update datasource link year display

package-lock.json, package.json, src/components/ExtraDataRightMenu/ExtraDataMenu.css, src/components/ExtraDataRightMenu/ExtraDataMenu.js, src/components/LeftHandMenu/LeftHandMenu.js, src/components/RightHandMenu/DonutChart/Donut.js
[Ticket](https://trello.com/c/Wf76mhOM/146-user-can-distinctively-see-how-to-toggle-between-secondary-data-within-the-dataset-dropdown)
- Moved secondary data below donut
- Turned secondary data into a dropdown component
- I grabbed the "react-dropdown" package so you'll have to run `npm i`
=> Secondary data dropdown

package-lock.json, src/components/RightHandMenu/DonutChart/UnEqualDonut/UnequalDonut.js
[Ticket](https://trello.com/c/9r1vHUVR/155-2a-data-state-update-food-insecurity-copy)
=> change copy on only food insecurity

src/App.css, src/components/RightHandMenu/DonutChart/Donut.css, src/components/RightHandMenu/DonutChart/Donut.js, src/components/RightHandMenu/DonutChart/UnEqualDonut/UnequalDonut.js
[ticket](https://trello.com/c/YPisjTS3/153-donut-update-align-styling)
Tried my best to match the donut styling for Poverty Rates and Food Insecurity (UnequalDonut.js) to the donut being used for WIC, Snap, and Race (Donut.js).
=> Donut update align styling

public/index.html, src/AllieAwesomeCSS.css, src/components/LeftHandMenu/DatasetSelector/DatasetSelector.css, src/components/LeftHandMenu/ZoomToBoundsMenu.css, src/components/LeftHandMenu/ZoomToBoundsMenu.js
Added new fonts and made some small CSS changes on the left side to make sure it all looked good!
=> New fonts final

src/App.js, src/components/LeftHandMenu/ZoomToBoundsMenu.js, src/components/MapColorLegend.js, src/components/RightHandMenu/LinkToSource/LinkToSource.js, src/mapbox/color-utils.test.js
Remove many of the warnings. Mostly unused variables and I simply commented out the ones that seemed like they could be relevant.
=> remove warnings

src/components/ExtraDataRightMenu/ExtraDataMenu.css
[Ticket](https://trello.com/c/1fNtapKC/174-onhover-state-for-dropdown)
=> change dropdown hover color to #CFD4D9

src/components/LeftHandMenu/ZoomToBoundsMenu.css, src/components/LeftHandMenu/ZoomToBoundsMenu.js
[Ticket](https://trello.com/c/hLmIZo3u/175-left-sidebar-selected-onhover-state)
=> add hover for left hand menu, and style active county selection

src/components/RightHandMenu/RightHandMenu.css
[Ticket](https://trello.com/c/y0GOZoXM/176-right-sidebar-should-not-display-a-horizontal-scroll-bar)
=> remove overflow:scroll

src/components/ExtraDataRightMenu/ExtraDataMenu.css, src/components/RightHandMenu/DonutChart/Legend/Legend.css, src/components/RightHandMenu/DonutChart/Legend/Legend.js, src/components/RightHandMenu/ToggleSelect/ToggleSelect.css
[Ticket](https://trello.com/c/Dp2Fi0AB/182-make-hand-cursor-styling-consistent-across)
=> Consistent cursor

src/components/ExtraDataRightMenu/ExtraDataMenu.css, src/components/ExtraDataRightMenu/ExtraDataMenu.js
[Ticket](https://trello.com/c/8trrarhi/180-dropdown-arrow-should-not-change-direction-under-show-data-for)
=> add is-open arrow rule

src/components/RightHandMenu/DonutChart/Legend/Legend.js
[Ticket](https://trello.com/c/0PEHLCIt/181-remove-total-population-data-line-under-out-of-total-population)
=> do not display 100% in food insecurity data

src/AllieAwesomeCSS.css, src/App.css, src/components/LeftHandMenu/ZoomToBoundsMenu.css, src/components/RightHandMenu/DonutChart/Donut.css, src/components/RightHandMenu/DonutChart/Legend/Legend.css, src/components/RightHandMenu/LinkToSource/LinkToSource.css, src/components/Utility/RadioSelect/RadioSelect.css
[Ticket](https://trello.com/c/sfUCAH3a/178-increase-font-sizes)
note: The left menu background gray was changed on this PR instead of another one. Sorry.
=> fix display data for font size, guess on all others

src/components/RightHandMenu/ToggleSelect/ToggleSelect.js
[ticket](https://trello.com/c/S9FfvEXK/188-clicking-the-toggle-button-a-second-time-breaks-data-display)
=> add if statement to prevent double click data bug

src/components/RightHandMenu/DonutChart/Legend/Legend.js
[ticket](https://trello.com/c/TWFhp2I6/185-user-cannot-select-or-hover-data-that-is-0-under-the-listed-data-below-the-donut-nor-should-it-display-in-the-donut)
=> clicking on option with 0 returns undefined
